#!/usr/bin/env bash
set -euo pipefail

# Based on: https://stackoverflow.com/a/24067243

# This file is a core part of makbet project.
# Do not change it, unless you know what you are doing.
#
# Params:
#
# ${1} - GNU_MAKE_REQUIRED_VER - Required version of GNU make tool.
# ${2} - GNU_MAKE_VER - Actual version of GNU make tool.

readonly GNU_MAKE_REQUIRED_VER="${1}"
readonly GNU_MAKE_VER="${2}"

if [[ "${GNU_MAKE_VER}" = "${GNU_MAKE_REQUIRED_VER}" ]]
then
    exit 0
else
    test "$(printf '%s\n' "${GNU_MAKE_REQUIRED_VER}" "${GNU_MAKE_VER}" | sort -V | head -n -1)" != "${GNU_MAKE_VER}"
    readonly rc=${?}

    if (( ${rc} == 0 ))
    then
        exit 0
    else
        echo "[INFO]: Checking required GNU make version..."
        echo "[INFO]: Required GNU make version: ${GNU_MAKE_REQUIRED_VER}"
        echo "[INFO]: Found: ${GNU_MAKE_VER}"
        echo "[ERROR]: Please update GNU make!"
        exit 1
    fi
fi


# End of file
