#!/usr/bin/env bash
set -u


# This file is a core part of makbet project.
# Do not change it, unless you know what you are doing.
#
# Params:
#
# ${1} - Path to makbet's scenario (typically Makefile) file.

# shellcheck disable=SC2016
grep -c '^$(eval $(call TASK_template' "${1}"


# EOF
