#!/usr/bin/env bash
# set -eu


# This file is a core part of makbet.
# Do not change it unless you know what you are doing.
#
# Params:
#
# ${1} - Path to makbet's scenario (make file) file.

# shellcheck disable=SC2016
grep -c '^$(eval $(call TASK_template' "${1}"


# End of file
