#!/usr/bin/env bash
set -u


set +e
if [ -d "${MAKBET_PATH}/.git" ]
then
    readonly LAST_COMMIT_DETAILS="$(git log -1 --format="g%h-%cI")"
    echo "$(cat "${MAKBET_PATH}/VERSION")-${LAST_COMMIT_DETAILS}"
else
    cat "${MAKBET_PATH}/VERSION"
fi
set -e


# End of file
