#!/usr/bin/env bash
set -eu


# This file is a core part of makbet project.
# Do not change it, unless you know what you are doing.
#
# Params:

set +e
if [ -d "${MAKBET_PATH}/.git" ]
then
    # shellcheck disable=SC2155
    readonly LAST_COMMIT_DETAILS="$(git log -1 --format="g%h-%cI")"
    echo "$(cat "${MAKBET_PATH}/VERSION")+${LAST_COMMIT_DETAILS}"
else
    cat "${MAKBET_PATH}/VERSION"
fi
set -e


# EOF
