#!/usr/bin/env bash
set -eu


# This file is a core part of makbet project.
# Do not change it, unless you know what you are doing.
#
# Params:
#
# ${1} - TASK_ID - Order number of task's definition.
# ${2} - TASK_NAME - The name of the task.
# ${3} - TASK_DEPS - All task dependencies.
# ${4} - TASK_CMD - Task command.
# ${5} - TASK_CMD_OPTS - Input options for TASK_CMD above.

printf "\
TASK_ID: %s
TASK_NAME: %s
TASK_DEPS: %s
TASK_CMD: %s
TASK_CMD_OPTS: %s
" "${1}" "${2}" "${3:-"None"}" "${4:-"None"}" "${5:-"None"}"


# EOF
