#!/usr/bin/env bash
set -eu


# This file is a core part of makbet project.
# Do not change it, unless you know what you are doing.
#
# Params:
#
# ${1} - TASK_ID - Order number of task's definition.
# ${2} - TASK_NAME - The name of the task.
# ${3} - TASK_DEPS - All task dendencies.
# ${4} - TASK_CMD - Task command.
# ${5} - TASK_CMD_OPTS - Input options for TASK_CMD above.
# ${6} - TASK_EVENT_FILE - Destination *.cfg event file.
# ${7} - TASK_EVENT_TYPE - The type of the event (STARTED or TERMINATED).

# shellcheck disable=SC2155
readonly NOW=$( date "+%Y-%m-%d %H:%M:%S.%N" )
# shellcheck disable=SC2155
readonly NOW_SHORT=$( date --date="${NOW}" "+%Y-%m-%d %H:%M:%S.%3N" )

# Create an empty *.cfg event results file.
echo -n "" > "${6}"

# Append data to *.cfg event results file.
# shellcheck disable=SC2129
printf "\
TASK_ID=\"%s\"
TASK_NAME=\"%s\"
TASK_DEPS=\"%s\"
TASK_CMD=\"%s\"
TASK_CMD_OPTS=\"%s\"
TASK_EVENT_TYPE=\"%s\"
TASK_DATE_TIME_%s=\"%s\"
" "${1}" "${2}" "${3}" "${4}" "${5}" "${7}" "${7}" "${NOW}" >> "${6}"

# Print console message.
echo -e "\n${NOW_SHORT} [INFO]: Task \"${2}\" (TASK_ID: ${1}) ${7,,}.\n"


# EOF
