#!/usr/bin/env bash
set -euo pipefail


# This file is a core part of makbet project.
# Do not change it, unless you know what you are doing.
#
# Params:
#
# ${1} - Path to *.started.cfg event file.
# ${2} - Path to *.terminated.cfg event file.
# ${3} - Path to results *.cfg file.

# Source input *.started.cfg event file.
# shellcheck source=/dev/null
. "${1}"

# Source input *.terminated.cfg event file.
# shellcheck source=/dev/null
. "${2}"

# Define T1 variable (read-only) - take TASK_DATE_TIME_STARTED
# value from "${1}" file and convert it to seconds.NANOSECONDS
# format ssssssssss.NNNNNNNNN for further calculations.
# shellcheck disable=SC2155
readonly T1=$( date --date="${TASK_DATE_TIME_STARTED}" +"%s.%N" )

# Define T2 variable (read-only) - take TASK_DATE_TIME_TERMINATED
# value from "${2}" file and convert it to seconds.NANOSECONDS
# format ssssssssss.NNNNNNNNN for further calculations.
# shellcheck disable=SC2155
readonly T2=$( date --date="${TASK_DATE_TIME_TERMINATED}" +"%s.%N" )

# Calculate T2 - T1 time difference and round it to three
# decimal places (milliseconds).
# shellcheck disable=SC2155
readonly TASK_DURATION=$( date --date="0 ${T2} sec - ${T1} sec" +"%Hh:%Mm:%Ss.%3Nms" )

# Create an emtpy results *.cfg file.
echo -n "" > "${3}"

# Save profiling data to results *.cfg file.
comm --nocheck-order "${1}" "${2}" \
    | grep -Pv "EVENT_TYPE" \
    | sed 's/^[ \t]*//' \
    > "${3}"
echo "TASK_DURATION=${TASK_DURATION}" >> "${3}"

# Print profiling results to the console.
echo "Profiling results:"
echo "T1 = ${T1}"
echo "T2 = ${T2}"
echo "T2 - T1 = ${TASK_DURATION}"


# End of file
