#!/usr/bin/env bash
set -eu


# ${1} - TASK_ID - Order number of task's definition.
# ${2} - TASK_NAME - The name of the task.
# ${3} - TASK_DEPS - All task dendencies.
# ${4} - TASK_CMD - Task command.
# ${5} - TASK_CMD_OPTS - Input options for TASK_CMD above.
# ${6} - TASK_EVENT_FILE - Destination *.cfg event file.
# ${7} - TASK_EVENT_TYPE - The type of the event (STARTED or TERMINATED).

readonly NOW=$( date "+%Y-%m-%d %H:%M:%S.%N" )
readonly NOW_SHORT=$( date --date="${NOW}" "+%Y-%m-%d %H:%M:%S.%3N" )

# Create an empty destination *.cfg event file.
echo -n "" > "${6}"

# Append data to destination *.cfg event file.
# shellcheck disable=SC2129
echo "TASK_ID=\"${1}\"" >> "${6}"
echo "TASK_NAME=\"${2}\"" >> "${6}"
echo "TASK_DEPS=\"${3}\"" >> "${6}"
echo "TASK_CMD=\"${4}\"" >> "${6}"
echo "TASK_CMD_OPTS=\"${5}\"" >> "${6}"
echo "TASK_EVENT_TYPE=\"${7}\"" >> "${6}"
echo "TASK_DATE_TIME_${7}=\"${NOW}\"" >> "${6}"

# Print console message.
echo -e "\n${NOW_SHORT} [INFO]: Task \"${2}\" (TASK_ID: ${1}) ${7,,}.\n"


# End of file
