#!/usr/bin/env bash
set -eu


# This file is a core part of makbet project.
# Do not change it, unless you know what you are doing.
#
# Params:
#
# ${1} - Path to input *.cfg file.
# ${2} - Path to output *.dot file.

# Source input *.cfg file.
# shellcheck source=/dev/null
. "${1}"

# Create new, empty *.dot file.
echo "" > "${2}"

#
# Add to file some task's details as a comments.
#
# shellcheck disable=SC2129
printf "\
// TASK_NAME: %s
// TASK_ID: %s
// TASK_DEPS: %s
// TASK_CMD: %s
// TASK_CMD_OPTS: %s
" "${TASK_NAME}" "${TASK_ID}" "${TASK_DEPS}" "${TASK_CMD}" "${TASK_CMD_OPTS}" >> "${2}"

# Append information about node and its dependencies (if there
# are any) to *.dot file created above.
if [ -z "${TASK_DEPS}" ]
then
    echo "\"${TASK_NAME}\";" >> "${2}"
else
    for t in ${TASK_DEPS}
    do
        echo "\"${TASK_NAME}\" -> \"${t}\";" >> "${2}"
    done
fi


# EOF
