#!/usr/bin/env bash
set -eu


# This file is a core part of makbet project.
# Do not change it, unless you know what you are doing.
#
# Params:
#
# ${1} - Path to *.started.cfg event file.
# ${2} - Path to *.terminated.cfg event file.
# ${3} - Path to results *.cfg file.

# shellcheck source=/dev/null
. "${1}" && . "${2}"

readonly T1=$( date --date="${TASK_DATE_TIME_STARTED}" +"%s.%N" )
readonly T2=$( date --date="${TASK_DATE_TIME_TERMINATED}" +"%s.%N" )
readonly TASK_DURATION=$( date --date="0 ${T2} sec - ${T1} sec" +"%Hh:%Mm:%Ss.%3Nms" )

echo "Profiling results:"
echo "T1 = ${T1}"
echo "T2 = ${T2}"
echo "T2 - T1 = ${TASK_DURATION}"

# Create an emtpy results *.cfg file.
echo -n "" > "${3}"

# Save profiling data to results *.cfg file.
comm --nocheck-order "${1}" "${2}" \
    | grep -Pv "EVENT_TYPE" \
    | sed 's/^[ \t]*//' \
    > "${3}"
echo "TASK_DURATION=${TASK_DURATION}" >> "${3}"


# End of file
