#!/usr/bin/env bash
set -eu


# This file is a core part of makbet project.
# Do not change it, unless you know what you are doing.
#
# Params:
#
# ${1} - Path to input *.cfg file.
# ${2} - Path to output *.dot file.

# shellcheck source=/dev/null
. "${1}"
echo "" > "${2}"
if [ -z "${TASK_DEPS}" ]
then
    echo "\"${TASK_NAME}\";" >> "${2}"
else
    for t in ${TASK_DEPS}
    do
        echo "\"${TASK_NAME}\" -> \"${t}\";" >> "${2}"
    done
fi


# End of file
