#!/usr/bin/env bash
# shellcheck disable=SC2002,SC2164
set -u
set -x


readonly output_file="${1}"
readonly expected_file="${2}"
pushd "${MAKBET_PATH}/examples/06.comments/" > /dev/null

make MAKBET_VERBOSE=0 scenario-help \
    > "${output_file}"

diff -u -s \
    <( \
        cat "${output_file}" \
        | nl -b a \
    ) \
    <( \
        cat "${expected_file}" \
        | nl -b a \
    )
readonly __rc=$?
popd > /dev/null
exit ${__rc}


# End of file
