#!/usr/bin/env bash
# shellcheck disable=SC2002,SC2164
set -u
set -x


readonly output_file="${1}"
readonly expected_file="${2}"
pushd "${MAKBET_PATH}" > /dev/null

make -f "${MAKBET_PATH}/examples/03.toolchain-advanced/Makefile" scenario-help \
    > "${output_file}"

diff -u -s \
    <( \
        cat "${output_file}" \
        | nl \
        | grep '\- Id.:  ' \
    ) \
    <( \
        cat "${expected_file}" \
        | grep '\- Id.:  ' \
    )
readonly __rc=$?
popd > /dev/null
exit ${__rc}


# EOF
