#!/usr/bin/env bash
# shellcheck disable=SC2002,SC2164
set -u
set -x


readonly output_file="${1}"
readonly expected_file="${2}"
pushd "${MAKBET_PATH}/examples/01.dummy/" > /dev/null
make makbet-clean && make -j8 MAKBET_DOT=1 all
make .show-summary-dot-file > "${output_file}"
diff -u -s \
    <( \
        cat "${output_file}" \
        | sed '1d;4,6d;10d;48d' \
        | nl -b a \
    ) \
    <( \
        cat "${expected_file}" \
        | sed '3,5d;9d' \
        | nl -b a \
    )
readonly __rc=$?
popd > /dev/null
exit ${__rc}


# End of file
