#!/usr/bin/env bash
# shellcheck disable=SC2002,SC2164
set -u
set -x


readonly output_file="${1}"
readonly expected_file="${2}"
pushd "${MAKBET_PATH}/examples/01.dummy" > /dev/null

make \
    > "${output_file}"

diff -u -s \
    <( \
        cat "${output_file}" \
        | sed '2d;8d;34d;47d;54d;61d;68d;75d;82d;89d;96d;103d;117d' \
        | nl -b a \
    ) \
    <( \
        cat "${expected_file}" \
        | sed '2d;8d;34d;47d;54d;61d;68d;75d;82d;89d;96d;103d;117d' \
        | nl -b a \
    )
readonly __rc=$?
popd > /dev/null
exit ${__rc}


# End of file
