#!/usr/bin/env bash
# shellcheck disable=SC2002,SC2164
set -u
set -x


readonly output_file="${1}"
readonly expected_file="${2}"
pushd "${MAKBET_PATH}" > /dev/null
make -f "${MAKBET_PATH}/examples/01.dummy/Makefile" > "${output_file}"
diff -u -s \
    <( \
        grep -Po '^Found \d* valid task\(s\) defined in /' \
        "${output_file}" \
    ) \
    <( \
        grep -Po '^Found \d* valid task\(s\) defined in /' \
        "${expected_file}" \
    )
readonly __rc=$?
popd > /dev/null
exit ${__rc}


# End of file
