#!/usr/bin/env bash
# shellcheck disable=SC2002,SC2164
set -u
set -x


readonly output_file="${1}"
readonly expected_file="${2}"
pushd "${MAKBET_PATH}/examples/01.dummy/" > /dev/null
make makbet-clean
make MAKBET_CSV=1 all

tree -F "${MAKBET_CACHE_DIR}" \
    > "${output_file}"

diff -u -s \
    <( \
        cat "${output_file}" \
        | sed '1d' \
        | nl -b a \
    ) \
    <( \
        cat "${expected_file}" \
        | sed '1d' \
        | nl -b a \
    )
readonly __rc=$?
popd > /dev/null
exit ${__rc}


# End of file
