name: CI

# Controls when the action will run.  Triggers the workflow on push
# or pull request events but only for "master" and "stable/v0.1.x"
# branches.
on:

  push:
    branches:
      - master
      - stable/v0.1.x

  pull_request:
    branches:
      - master
      - stable/v0.1.x

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel.
jobs:

  # This workflow contains a single job called "build".
  build:

    # The type of runner that the job will run on.
    # More details about SW installed on "ubuntu-latest" runner
    # can be found on below page:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed
    # as part of the job.
    steps:

      - name: Install tree utility...
        run: sudo apt-get install tree

      - name: Check tree version...
        run: tree --version

      - name: Check GNU Make version...
        run: make --version

      - name: Check bash version...
        run: bash --version

      # Checks-out the repository under ${GITHUB_WORKSPACE}, so all
      # jobs can access it.
      - uses: actions/checkout@v2

      - name: Run makbet's test suite...
        run: |
          cd tests/
          ./run-tests.sh
          echo $?

      # Archive tests/logs/ + tests/output/ in artifacts.zip file.
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            tests/logs/
            tests/output/


# End of file
